# Machine_learning

In [2]:
import pandas as pd 
import seaborn as sns 
import matplotlib as plt # libs are important.

In [6]:
df_raw = pd.read_csv(r"C:\Users\prabh\Code_Basic\64101194a2364\source-code\2_pandas_basics_code\2_dataframe_basics\Exercise\bengaluru_house_prices.csv")
df_raw.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0

In [8]:
df = df_raw[['total_sqft', 'price']]
df.head()

   total_sqft  price
0        1920  121.0
1        1500  192.0
2         925   55.0
3         500   55.0
4        1174   74.0

In [19]:
df['price_lakhs'] = df['price']

C:\Users\prabh\AppData\Local\Temp\ipykernel_4480\3497334109.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_lakhs'] = df['price']

In [20]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(df[['total_sqft']], df['price_lakhs'])

LinearRegression()

In [21]:
model.predict([[1500],[1900],[432]])

C:\Users\prabh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([ 90.41484545, 121.61920388,   7.09920842])

In [22]:
model.coef_ , model.intercept_

(array([0.0780109]), -26.601498695563066)

In [ ]:
Now try in Y = mx + b. Y - price_lakhs , M slope coef_ ,  B - intercept , X - Total_sqft.

In [25]:
derive_price_lakhs = model.coef_[0]*1500 + (model.intercept_)
derive_price_lakhs

90.41484544627394

In [26]:
derive_price_lakhs = model.coef_[0]*432 + (model.intercept_)
derive_price_lakhs

7.099208417285993

#### This was a single linear regression. Now for Multiple linear . Adding Bedroom.

In [27]:
df_raw.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0

In [34]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     50 non-null     object
 1   availability  50 non-null     object
 2   location      50 non-null     object
 3   size          50 non-null     object
 4   society       30 non-null     object
 5   total_sqft    50 non-null     int64
 6   bath          50 non-null     float64
 7   balcony       50 non-null     float64
 8   price         50 non-null     float64
dtypes: float64(3), int64(1), object(5)
memory usage: 3.6+ KB

In [33]:
df_raw.describe()

        total_sqft      bath    balcony       price
count    50.000000  50.00000  50.000000   50.000000
mean   1393.040000   2.36000   1.680000   82.070800
std     635.497297   0.89807   0.843704   62.645493
min     410.000000   1.00000   0.000000   16.450000
25%    1116.250000   2.00000   1.000000   46.000000
50%    1239.000000   2.00000   2.000000   57.400000
75%    1500.000000   3.00000   2.000000   80.750000
max    3600.000000   5.00000   3.000000  350.000000

In [37]:
df_raw['BHK'] = df_raw['size'].str.extract(r'(\d+)').astype(int)
df_raw.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,BHK
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0,3
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0,4
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0,2
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0,2
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0,2

#### From size extracted the BHK, Bedroom into BHK number

In [39]:
df_norm = df_raw[['total_sqft', 'price','BHK']]
df_norm.head()

   total_sqft  price  BHK
0        1920  121.0    3
1        1500  192.0    4
2         925   55.0    2
3         500   55.0    2
4        1174   74.0    2

In [43]:
model = LinearRegression()
model.fit(df_norm[['total_sqft','BHK']], df_norm['price'])

LinearRegression()

In [44]:
model.predict([[1800,3]])

C:\Users\prabh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([113.79648918])

In [45]:
model.predict([[2300,4]])

C:\Users\prabh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([151.5631678])

In [49]:
price_in_lakhs = model.predict([[2003, 2]])[0]
price_in_lakhs

C:\Users\prabh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

133.04931193003694

In [50]:
model.coef_ , model.intercept_

(array([ 0.08110882, -2.78773203]), -23.836193070525937)

In [52]:
test = pd.DataFrame([
    {"total_sqft":1590,"BHK":2},
    {"total_sqft":1999,"BHK":4}
])

In [62]:
model.predict(test)

array([ 99.55136874, 127.14941259])

### Y = m.total_area + m.BHK + B

In [63]:
price_bhk = model.coef_[0]*1590 + model.coef_[1]*2 + model.intercept_
price_bhk

99.55136873572529